[package]
name = "oxide-ci"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
ignore = "0.4.25"
indicatif = "0.18.4"
rayon = "1.11.0"
regex = "1.12.3"
tokio = { version = "1.49.0", features = ["full"] }
